version: '3.4'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  test:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 19000:19000
    depends_on:
      - redis
