## ?? ??
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  port: 9092


## DB Connect test
spring:
  datasource:
    hikari:
      maximum-pool-size: 4

    url: jdbc:postgresql://localhost:5432/java
    username: y_chan
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql=true: