# Log level setting
# package ?? ?? ??.
#logging:
#  level:
#    hello:
#      springmvc=info


# default setting
# ???? ?? ??? ?? ???? ???.
logging:
  level:
    root: info


#
### thymeleaf default setting
### ??? ?? ?? ? ? ? ??.
#spring:
#  thymeleaf:
#    prefix: classpath:/test/
#    suffix: .html

